[package]
name = "systemprompt-users"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Core user management module for systemprompt.io"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
inventory = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

systemprompt-database = { path = "../../infra/database", version = "0.0.4" }
systemprompt-extension = { path = "../../shared/extension", version = "0.0.4" }
systemprompt-identifiers = { path = "../../shared/identifiers", version = "0.0.4", features = ["sqlx"] }
systemprompt-models = { path = "../../shared/models", version = "0.0.4" }
systemprompt-provider-contracts = { path = "../../shared/provider-contracts", version = "0.0.4" }
systemprompt-traits = { path = "../../shared/traits", version = "0.0.4" }