[package]
name = "systemprompt-identifiers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Core identifier types for SystemPrompt OS"

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
schemars = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
