[package]
name = "systemprompt-core-files"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "File management module for SystemPrompt"

[lints]
workspace = true

[dependencies]
systemprompt-cloud = { path = "../../infra/cloud" }
systemprompt-core-database = { path = "../../infra/database" }
systemprompt-core-logging = { path = "../../infra/logging" }
systemprompt-models = { path = "../../shared/models" }
systemprompt-identifiers = { path = "../../shared/identifiers" }
systemprompt-traits = { path = "../../shared/traits" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
walkdir = "2"
tracing = { workspace = true }
async-trait = { workspace = true }
inventory = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
